services:
  - type: web
    name: webapplication1-service
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/WebApplication1.dll
    branch: main
    region: singapore  # 可改成 oregon、frankfurt 等

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DB_CONNECTION
        value: Host=localhost;Port=5432;Username=fake;Password=fake;Database=fake
