services:
  - type: web
    name: webapplication1-service
    env: docker
    plan: free
    branch: main
    region: singapore
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DB_CONNECTION
        value: Host=localhost;Port=5432;Username=fake;Password=fake;Database=fake
